# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b21cdb81a76e3f03c50c1f6e639503c275b300a73753913a6bf6d8ce86a0795e9ce677771ea45ec0f8e6c20818f2630072e41d2a4ae16942698117e2f0579d3c

test:
  secret_key_base: d963014c220205d6e8abe733401ce18df80e60df94ffe1f13241109469641813d3eb8391522f986797c6ab4bd7c956f42628a034fa04d249ff00f42ceafdb784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
